name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CC: clang-22
  CXX: clang++-22


jobs:
  build:
    runs-on: ubuntu-26.04

    steps:

    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-22 libclang-22-dev libclang-cpp22-dev llvm-22-dev libcurl4-openssl-dev
        mkdir build

    - name: Build
      working-directory: ./build
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE:BOOL=Release ..
        ninja
        ls Products/
