name: C++ CI

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

env:
  CC: clang-22
  CXX: clang++-22


jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-22 libclang-22-dev libclang-cpp22-dev llvm-22-dev libcurl4-openssl-dev
        mkdir build

    - name: Build
      working-directory: ./build
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE:BOOL=Release \
          -DBUILD_TESTING:BOOL=ON  \
          -DCPACK_BINARY_TGZ:BOOL=ON -DCPACK_BINARY_STGZ:BOOL=OFF -DCPACK_BINARY_TZ:BOOL=OFF \
          ..
        ninja package

    - name: Run Tests
      shell: bash
      working-directory: ./build
      run: |
        ctest -j $(nproc) --output-on-failure

    - name: Archive TGZ artifact
      uses: actions/upload-artifact@v7
      with:
        name: EnergyPlus-clang-tools-${{ github.sha }}.tar.gz
        path: build/EnergyPlus-clang-tools-*.tar.gz

    - name: Upload Binary installer to release
      if: contains(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v3
      with:
        files: build/EnergyPlus-clang-tools-*.tar.gz
